### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Dejv311** [dpjudas/UT99VulkanDrv#13]
Hi there,
so I would like to run Unreal Tournament at 2K with my potato PC, thus I came to the conclusion that vulkan could help. Afterall I tried to run minecraft at 2K and it worked fine. UE99 with openGL struggles though.

Anyways I tried compiling your code and I am just lost. I downloaded VS Community 2019, opened the project, then I had to click "reload" on the project for some reason (that took me like 2 hours to figure out). Then it finally let me build the project, but it failed on "Engine.h" not found. I looked around the project and found out, that it was looking for the file in:

```
$(ProjectDir);$(SolutionDir)Thirdparty\UnrealTournamentSDK\Core\Inc;
$(SolutionDir)Thirdparty\UnrealTournamentSDK\Engine\Inc;
```

but the file was actually in:

```
$(SolutionDir)Thirdparty\ut432pubsrc\Core\Inc;
$(SolutionDir)Thirdparty\ut432pubsrc\Engine\Inc;
```

After that the compilation finished a little bit later with 445 errors and 485 warnings. And that is the point where I give up and kindly ask you for guidance. I guess I need to get the "UnrealTournamentSDK" somewhere, but I have no idea where.

**Comment by dpjudas** [comment]
I'm sorry, but you are unable to compile this project anymore due to dependency to 469 SDK, which to my knowledge is not publicly available. For that reason I can't bundle it in the project like I did with 432.

**Comment by Dejv311** [comment]
So is there any way for me to use this project (Acquire the SDK/get precompiled dll/...) or am I just stuck with opengl?

**Comment by dpjudas** [comment]
You can use the binaries that are provided for each release. You could also try ask the 469 team if you can get access to the 469 SDK. Last option is to use an earlier version (the 1.x series) that used the 432 SDK.

**Comment by Dejv311** [comment]
Oh... I just noticed in the "tags" submenu... I would suggest you mention that in the readme so that people notice the download containing VulkanDrv.dll, which is not currently present in source of the main branch.

Thank you for your help.

**Comment by Mis012** [comment]
>closed this as completed 28 days ago

uhm, it still doesn't compile...

It should be fully possible to replace all the "proprietary" parts with stubs, which would only be similar to the real code as much as required for binary compatibility

obviously one could do that even without access to the real code, but it would be a lot easier to do for someone *with* the access

**Comment by dpjudas** [comment]
I didn't bother make the 469b dependency optional because 436 is extremely broken on modern computers.

As for duplicating the proprietary headers with something that will still make it compile, while that is technically possible it would require way too much time. If you really want to build it yourself, convince the 469 team to release a public SDK - or try get a copy of the SDK by asking someone from the 469 team.
