### ISSUE TITLE
Lodbias

### ISSUE THREAD

**Issue by giresun27** [dpjudas/UT99VulkanDrv#14]
Hi is it possible to add lodbias to your vulkan renderer? I use high lodbias for the world detail to be low and clear I can use that option on all other renderers if it is possible please let me know

**Comment by dpjudas** [comment]
Sure, I'll add an LODBias option in the next update.

**Comment by giresun27** [comment]
Thanks I will be waiting in anticipation

**Comment by giresun27** [comment]
Can you also add oneXblending?

**Comment by dpjudas** [comment]
Added LODBias and OneXBlending to v2.1

**Comment by giresun27** [comment]
Hey WOW!
Thank you very much.
Now I have to wait for it to be whitelisted by ACE on the UT servers ACE kicks me out on the new version.

Thanks again.
