### ISSUE TITLE
Strange shading

### ISSUE THREAD

**Issue by BerserkerBG** [dpjudas/UT99VulkanDrv#17]
I noticed some strange shadow shading in Vulkan:
![Screenshot_168](https://user-images.githubusercontent.com/58362332/206938011-0ae72708-1803-47eb-acf3-54936cf07008.png)

Compared to other renderers:
![Screenshot_169](https://user-images.githubusercontent.com/58362332/206937975-db5ca5e8-47f4-4534-a057-682448761e10.png)

**Comment by dpjudas** [comment]
This most likely has to do with the way it clamps the darkest shades in textures to avoid certain visual artifacts elsewhere in UT. I don't intend to fix this as I'm already tired of trying to read the other render devices code to look for some one-liner somewhere that makes all the difference. Sorry. :)

**Comment by BerserkerBG** [comment]
![image (1)](https://github.com/dpjudas/UT99VulkanDrv/assets/58362332/ad6c9c4e-0790-4d6f-92b9-d4f740fdfc7c)
