### ISSUE TITLE
Vulkan Low Saturation

### ISSUE THREAD

**Issue by BerserkerBG** [dpjudas/UT99VulkanDrv#18]
I really like there is a VkSaturation option, it's really great that it lets you control it, but it seems like the range between 0 and 1 is not enough. 1 Seems to be the maximum saturation it can do. Here is how it looks like on VkSaturation=1
![Screenshot_168](https://user-images.githubusercontent.com/58362332/206939109-c9a7ce23-0585-47f6-98f1-b641e64177e5.png)

Here are other renderers for comparison:
![Screenshot_169](https://user-images.githubusercontent.com/58362332/206939128-8cb511e7-699f-4f39-9479-6bd10ebedabf.png)

**Comment by dpjudas** [comment]
These saturation/brightness/contrast settings originate from GZDoom. There is a GrayFormula setting that can be set to 0, 1 or 2. I'm not entirely sure what the difference is between them.

Something does seem to be odd though. The HUD doesn't seem to be saturated on your screenshot (it is still blue). I'll try look into that at some point to find out what is up with that.

**Comment by l0m-dev** [comment]
The problem is that the saturation is clamped to 0.8 and not 1.0.

`clamp(VkSaturation, -0.8f, 0.8f);`

Maybe even make the maximum 1.5 for those who prefer higher saturation.
