### ISSUE TITLE
GammaCorrectScreenshots=False or True Option.

### ISSUE THREAD

**Issue by thiagoobr** [dpjudas/UT99VulkanDrv#20]
Hi man,

Could you put this correction so when you take a shott, it comes out with the correct color and clarity?

![WhatsApp_Image_2023-03-28_at_21 54 33](https://user-images.githubusercontent.com/82742656/228705066-ae22fbd5-ae1d-444c-9eb6-73724bb8087e.jpeg)
![Shot00001](https://user-images.githubusercontent.com/82742656/228705073-bf9736e3-9cf7-4a80-951b-e83007cf4b5e.png)

**Comment by thiagoobr** [comment]
hi,
In other drivers that have this option, the print comes out correctly...
I couldn't make the print stay in the color shown on the screen at all with vulkan...
if you can give me any advice i will be grateful...

**Comment by dpjudas** [comment]
Should be working better now.
