### ISSUE TITLE
alt tab bug

### ISSUE THREAD

**Issue by louisjebril** [dpjudas/UT99VulkanDrv#22]
alt tabbing with vulkan renderer (2.4 and 2.5) doesnt minimize ut, game stays on top
it shows cursor and i can use it on second monitor
with d3d11 renderer (2.4 and 2.5) minimizing works but tabbing back into game makes cursor appear here and there and if going too far right the cursor goes on second monitor, can even click stuff on desktop

**Comment by utgoat** [comment]
blackscreen after minimizing on d3d11 is happening for me.

**Comment by an-eternity** [comment]
> blackscreen after minimizing on d3d11 is happening for me.

Same is happening on my test system (Windows 11 22H2, AMD graphics driver 22.11.2, UT99 v469d-rc2, D3D11Drv version 2.5).
But then, if switch to windowed mode from that *blackscreen state*, and then back to fullscreen from windowed mode, then it works...
