### ISSUE TITLE
UT Black (really black)

### ISSUE THREAD

**Issue by VirgileVILE** [dpjudas/UT99VulkanDrv#29]
I wanted to test the v469e-test425 build with Vulkan, and I don't know why, the game is plunged into darkness, except for objects that appear normally. I can no longer play under Vulkan...
![Shot00000](https://github.com/dpjudas/UT99VulkanDrv/assets/33984732/0d837f89-61f6-4ec3-b675-b85938eeb062)

**Comment by dpjudas** [comment]
Oops, made a last minute change I forgot to test. Released a new version that should work now.
