### ISSUE TITLE
 D3D11 renderer - screenshots look dark

### ISSUE THREAD

**Issue by Annonymous5542** [dpjudas/UT99VulkanDrv#34]
hello, 

I've been running some comparison tests between this and other renderers, in part using in-game screenshots. Just something I noticed is that the screenshot command in-game ends up generating a dark image - using too much contrast compared to how the game actually looks.

It's just something I noticed. Using this D3D11 renderer as default since the game looks and works better on my system so I like it a lot. 

Taken using the "shot" command.
![screenshot](https://github.com/dpjudas/UT99VulkanDrv/assets/124473650/b25667aa-baba-4980-89bf-43b60329e0ba)

**Comment by dpjudas** [comment]
Is GammaCorrectScreenshots enabled in UnrealTournament.ini?

**Comment by Annonymous5542** [comment]
Looks like that was it. Set GammaCorrectScreenshots=False and they look more like it. Thank!

**Comment by Annonymous5542** [comment]
> Is GammaCorrectScreenshots enabled in UnrealTournament.ini?

Looks like that was it. Set GammaCorrectScreenshots=False and they look more like it. Thanks!
