### ISSUE TITLE
Vulkan Renderer threading Question

### ISSUE THREAD

**Issue by chris-mcc** [dpjudas/UT99VulkanDrv#6]
Does the Vulkan renderer take better advatage of more cores?

What are the improvements over using OpenGL with UT99?

**Comment by dpjudas** [comment]
The vulkan renderer is single threaded like all the other renderers.

It has no improvements over the OpenGL renderer. My motivation for writing it was to gain some understanding of how UT renders things (for my UTEngine project).

On my computers the UT99 OpenGL drivers have always been somewhat flaky in performance, so I've historically been using the D3D10 driver. However recently that one started to stutter badly on my Windows 10 machine - the vulkan driver solved that problem for me.  That's not to say this couldn't also been solved by the newer OpenGL drivers. I've just been burnt enough for those in the past that I prefer not to use them if I can avoid it.

With that said, there's no doubt that the 469 OpenGL drivers have a much larger feature set than the vulkan driver. If your goal is to get the most feature complete driver, then those are the best ones to use.

**Comment by chris-mcc** [comment]
Yeah, historically the openGL driver never really performed as well as the directX one.

The latest Xopengl hotfix 2 from the 469B patch does well but the direct x 11 renderer is better.

but I actually prefer the Vulkan one cos it's noticably smoother and consistent to me.  

Are there any other features you're looking to add to the Vulkan renderer?

**Comment by dpjudas** [comment]
I have considered adding ambient occlusion using the RTX feature available in vulkan.

There is also the option of ignoring the lightmaps completely and calculate the light in real time. However those things are blocked by the visuals in UTEngine not being correct. I really have to do the calculations perfectly for me to be able to ignore the lightmaps and use the playsim light sources directly as input. If I were to succeed in this then the light quality could reach a completely new level, but we are far away from that and we might never get there. Maybe some day. :)

**Comment by chris-mcc** [comment]
Mm, I was saying that's one of the last bits to the UT engine that could need improving.

They're adding high-res fonts in the next patch.

Oh, is your UTEngine available in 64bit? Are there benefits running in 64bit?

**Comment by dpjudas** [comment]
Yes, UTEngine is a 64-bit application. It can actually run on anything, including ARM. Note that UTEngine is just a hobby project of mine that is far from being usable for actually playing UT. UTEngine is my own rewrite of the entire unreal engine from scratch - it doesn't use the Unreal Engine 1 like the 469 project does.
