### ISSUE TITLE
Max Lighting not getting as bright as the dx9 or xopengl renderer

### ISSUE THREAD

**Issue by chris-mcc** [dpjudas/UT99VulkanDrv#8]
With a new UT99 patch, 469C RC2 being released I've been playing around with the different renderers as they've improved.

I noticed that the max brightness in the Vulkan renderer is lower than the others.   They both go correctly completely dark at basically the same point.
![UT_D3D9](https://user-images.githubusercontent.com/11029841/180621213-7768ccf9-c428-41c2-a618-cbb0bab0b60b.jpg)
![UT_Vulkan](https://user-images.githubusercontent.com/11029841/180621214-10ba2071-016f-40c3-8ac7-732ea0c78876.jpg)

First one is dx9, the second is the vulkcan renderer.

Would this be a white light limit? What do you think?

**Comment by dpjudas** [comment]
Hmm yeah, you're right. The Direct3D renderer actually doubles the strength of the lightmaps so that they can overbright.

I released a new version that fixes this along with the weapon clipping bug for the redeemer.

**Comment by chris-mcc** [comment]
Pretty hard to spot the difference now.  The shadows seem to be a touch too bright.
![xopengl_intheshade](https://user-images.githubusercontent.com/11029841/180625659-bd2fafd7-df3b-46f6-8875-39a755e0e92d.jpg)


![vulkan16_intheshade](https://user-images.githubusercontent.com/11029841/180625664-4e0017eb-6aed-43f5-8259-16c7ba60653e.jpg)

First is xopengl , second is vulkcan 
If you look at the box in the bottom right ish you'll notice the shadows are not quite as dark.  Not sure why.

Anything spring to mind?

**Comment by dpjudas** [comment]
I'm afraid not. Only way I can get it a bit closer to that is if I subtract a bit of light for the lightmaps overall.

**Comment by chris-mcc** [comment]
Ah, so no changiong the rate of decay for the lighting?  Mm, I've asked in the discord server if the xopengl renderer does something special.

**Comment by dpjudas** [comment]
I created a 1.7 release with slightly darker light maps. This is probably about as good as it is going to get. It is quite possible that render device does something special if the D3D ones don't look alike. In any case, I don't know what is different, so I can't fix it.

**Comment by chris-mcc** [comment]
Oh, I can't tell the difference anymore.  Thast's pretty much spot unless we discovered if it does anything special.

I'll have a more complete gander tomorrow.
